[package]
name = "supply-chain-transparency"
version = "0.1.0"
edition = "2021"

[dependencies]
ic-cdk = "0.12"
ic-cdk-macros = "0.8"
candid = "0.10"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1 